ignore:
  urls:
    - https://www.thepolyglotdeveloper.com/*
    - https://www.npmjs.com/package/@ionic/angular
    - https://www.npmjs.com/package/@robsonos/ionic-mdi
    - https://www.reddit.com/r/ionic/
